int32 player_number  # Player number of the robot
string action_type   # Motion command action of the robot
float64 pos_x        # X-coordinate of the robot
float64 pos_y        # Y-coordinate of the robot
float64 heading      # Heading of the robot (radians)
float64 vel_forward  # Forward velocity of the robot
float64 vel_left     # Leftward velocity of the robot
float64 vel_turn     # Turning velocity of the robot
float64 yaw          # Head yaw of the robot
float64 ball_pos_x   # Perceived X-coordinate of the ball
float64 ball_pos_y   # Perceived Y-coordinate of the ball

